

CREATE TABLE CUSTOMER 
 ( AP_REGNO varchar(100) not null, 
 CU_NAME varchar(50),
 CU_GENDER char(1),
 CU_ALAMAT varchar(255),
 CU_KTP varchar(16), 
 CU_PROP varchar(5),
 CU_AREA varchar(10),
 primary key (AP_REGNO) 
);
INSERT INTO CUSTOMER VALUES (NEWID(), 'Arighi', 'L','Jl. Melati No 77', '1234567890123456', 'MOB', '03')
INSERT INTO CUSTOMER VALUES (NEWID(), 'Novi', 'P','Jl. Anggrek No 64', '6543210987654321', 'MOB', '01')
INSERT INTO CUSTOMER VALUES (NEWID(), 'Lisa', 'P','Jl. Anggrek No 64', '6152430495867191', 'MTR', '05')

CREATE TABLE RFGENDER 
 ( GENDERCODE char(1) not null, 
 GENDERDESC varchar(10),
 primary key (GENDERCODE)
 )
INSERT INTO RFGENDER VALUES ('L', 'Laki-laki')
INSERT INTO RFGENDER VALUES ('P', 'Perempuan') 

CREATE TABLE ENUMSTAGE 
 ( STAGE varchar(5) not null, 
 STAGEDESC varchar(50),
 primary key (STAGE)
 ) 
 INSERT INTO ENUMSTAGE VALUES ('ANL', 'Analyst') 
 INSERT INTO ENUMSTAGE VALUES ('APR','Approval')
 INSERT INTO ENUMSTAGE VALUES ('DE','Data Entry')
 INSERT INTO ENUMSTAGE VALUES ('RDE','Review Data Entry')
 INSERT INTO ENUMSTAGE VALUES ('SDE','Short Data Entry')


 CREATE TABLE RFAREA 
 ( AREAID char(3) not null, 
 AREANAME varchar(50),
 primary key (AREAID)
 ) 
 INSERT INTO RFAREA VALUES ('01','Sector 1')
 INSERT INTO RFAREA VALUES ('02','Sector 2')
 INSERT INTO RFAREA VALUES ('03','Sector 3')
 INSERT INTO RFAREA VALUES ('04','Sector 4')
 INSERT INTO RFAREA VALUES ('05','Sector 5')

 CREATE TABLE RFPROPERTY 
 ( PROPERTYID varchar(5) not null, 
 PROPERTYNAME varchar(50),
 primary key (PROPERTYID)
 ) 
 INSERT INTO RFPROPERTY VALUES ('MOB','Mobil')
 INSERT INTO RFPROPERTY VALUES ('MTR','Motor')
 
  CREATE TABLE CUSTOMER_PROCESS 
 ( AP_REGNO varchar(100) not null, 
 STAGE varchar(5) not null,
 CU_NAME varchar(50), 
 CU_PROP varchar(5),
 primary key (AP_REGNO,STAGE)
 ) 
 INSERT INTO CUSTOMER_PROCESS VALUES ('F2D7C37D-97D5-4043-8BB9-E4AFFBFE7E42','DE','Arighi','MOB')
 INSERT INTO CUSTOMER_PROCESS VALUES ('F2D7C37D-97D5-4043-8BB9-E4AFFBFE7E42','SDE','Arighi','MOB')
 INSERT INTO CUSTOMER_PROCESS VALUES ('33881B7F-9F7C-4BD1-BD9E-8C7516B61AE6','DE','Novi','MOB')
 INSERT INTO CUSTOMER_PROCESS VALUES ('33881B7F-9F7C-4BD1-BD9E-8C7516B61AE6','SDE','Novi','MOB')
 INSERT INTO CUSTOMER_PROCESS VALUES ('33881B7F-9F7C-4BD1-BD9E-8C7516B61AE6','RDE','Novi','MOB')
 INSERT INTO CUSTOMER_PROCESS VALUES ('89A68EDB-20FB-4C75-BDF2-E96B335B8EF1','DE','Lisa','MTR')
